const accessoriesTags: string[] = [
    'jewelry',
    'watches',
    'sunglasses',
    'handbags',
    'wallets',
    'belts',
    'hats',
    'scarves',
    'gloves',
    'hair accessories',
    'ties',
    'bow ties',
    'socks',
    'leggings',
    'stockings',
    'tights',
    'umbrellas',
    'keychains',
    'phone cases',
    'headphones',
    'earphones',
    'earrings',
    'necklaces',
    'bracelets',
    'rings',
    'brooches',
    'pins',
    'watches',
    'watch bands',
    'sunglasses',
    'eyeglasses',
    'reading glasses',
    'prescription glasses',
    'handbags',
    'tote bags',
    'clutches',
    'crossbody bags',
    'backpacks',
    'shoulder bags',
    'wallets',
    'card holders',
    'coin purses',
    'belts',
    'waist belts',
    'hip belts',
    'hats',
    'caps',
    'beanies',
    'fedoras',
    'sun hats',
    'visors',
    'scarves',
    'wool scarves',
    'cashmere scarves',
    'silk scarves',
    'cotton scarves',
    'gloves',
    'leather gloves',
    'wool gloves',
    'cashmere gloves',
    'fingerless gloves',
    'hair accessories',
    'hair clips',
    'hair bands',
    'hair ties',
    'headbands',
    'ties',
    'bow ties',
    'silk ties',
    'cotton ties',
    'wool ties',
    'socks',
    'ankle socks',
    'crew socks',
    'knee-high socks',
    'thigh-high socks',
    'leggings',
    'patterned leggings',
    'printed leggings',
    'athletic leggings',
    'stockings',
    'fishnet stockings',
    'lace stockings',
    'opaque stockings',
    'tights',
    'patterned tights',
    'opaque tights',
    'sheer tights',
    'umbrellas',
    'compact umbrellas',
    'bubble umbrellas',
    'transparent umbrellas',
    'keychains',
    'keyrings',
    'phone cases',
    'phone wallets',
    'phone grips',
    'headphones',
    'earphones',
    'Bluetooth headphones',
    'wireless earphones',
  ];
  
  console.log(accessoriesTags);
  