const accessoriesTags: string[] = [
    'jewelry',
    'watches',
    'sunglasses',
    'handbags',
    'wallets',
    'belts',
    'hats',
    'scarves',
    'gloves',
    'hair accessories',
    'ties',
    'bow ties',
    'socks',
    'leggings',
    'stockings',
    'tights',
    'umbrellas',
    'keychains',
    'phone cases',
    'headphones',
    'earphones',
    'earrings',
    'necklaces',
    'bracelets',
    'rings',
    'brooches',
    'pins',
    'watches',
    'watch bands',
    'sunglasses',
    'eyeglasses',
    'reading glasses',
    'prescription glasses',
    'handbags',
    'tote bags',
    'clutches',
    'crossbody bags',
    'backpacks',
    'shoulder bags',
    'wallets',
    'card holders',
    'coin purses',
    'belts',
    'waist belts',
    'hip belts',
    'hats',
    'caps',
    'beanies',
    'fedoras',
    'sun hats',
    'visors',
    'scarves',
    'wool scarves',
    'cashmere scarves',
    'silk scarves',
    'cotton scarves',
    'gloves',
    'leather gloves',
    'wool gloves',
    'cashmere gloves',
    'fingerless gloves',
    'hair accessories',
    'hair clips',
    'hair bands',
    'hair ties',
    'headbands',
    'ties',
    'bow ties',
    'silk ties',
    'cotton ties',
    'wool ties',
    'socks',
    'ankle socks',
    'crew socks',
    'knee-high socks',
    'thigh-high socks',
    'leggings',
    'patterned leggings',
    'printed leggings',
    'athletic leggings',
    'stockings',
    'fishnet stockings',
    'lace stockings',
    'opaque stockings',
    'tights',
    'patterned tights',
    'opaque tights',
    'sheer tights',
    'umbrellas',
    'compact umbrellas',
    'bubble umbrellas',
    'transparent umbrellas',
    'keychains',
    'keyrings',
    'phone cases',
    'phone wallets',
    'phone grips',
    'headphones',
    'earphones',
    'Bluetooth headphones',
    'wireless earphones',
    'backpacks',
  'tote bags',
  'briefcases',
  'socks',
  'ties',
  'umbrellas',
  'hair accessories',
  'eyewear',
  'handkerchiefs',
  'caps',
  'beanies',
  'glasses',
  'purses',
  'clutches',
  'earrings',
  'necklaces',
  'bracelets',
  'rings',
  'cufflinks',
  'bow ties',
  'keychains',
  'phone cases',
  'luggage',
  'travel accessories',
  'scarf',
  'gloves',
  'Europe',
  'North America',
  // Accessory brands in EU
  'Louis Vuitton',
  'Gucci',
  'Hermes',
  'Chanel',
  'Prada',
  'Dior',
  'Burberry',
  'Fendi',
  'Valentino',
  'Balenciaga',
  'Celine',
  'Givenchy',
  'Yves Saint Laurent',
  'Alexander McQueen',
  'Loewe',
  'Bottega Veneta',
  'Miu Miu',
  'Versace',
  'Jimmy Choo',
  'Kenzo',
  'Moschino',
  'Off-White',
  'Rimowa',
  'Longchamp',
  'Maison Margiela',
  'Bally',
  // Accessory brands in North America
  'Michael Kors',
  'Coach',
  'Kate Spade',
  'Tory Burch',
  'Marc Jacobs',
  'Calvin Klein',
  'Ralph Lauren',
  'Tommy Hilfiger',
  'Vera Bradley',
  'Fossil',
  'Guess',
  'Dooney & Bourke',
  'Cole Haan',
  'Rebecca Minkoff',
  'Nordstrom',
  'Saks Fifth Avenue',
  'GAP',
  'Banana Republic',
  'J.Crew',
  'Lululemon',
  'Under Armour',
  'The North Face',
  'Patagonia',
  'Columbia',
  'Oakley',
  'Ray-Ban',
  'Nixon',
  'Timex',
  'Casio',
  'Vans',
  'Converse',
  'New Era',
  ];
  
  console.log(accessoriesTags);
  