const artCraftTags: string[] = [
    'paint',
    'canvas',
    'brushes',
    'sketchbooks',
    'colored pencils',
    'markers',
    'watercolor',
    'acrylic paint',
    'oil paint',
    'charcoal',
    'pastels',
    'drawing pens',
    'craft paper',
    'scissors',
    'glue',
    'craft paint',
    'glitter',
    'craft foam',
    'beads',
    'embroidery floss',
    'sewing machine',
    'yarn',
    'knitting needles',
    'crochet hooks',
    'felt',
    'ribbons',
    'buttons',
    'sequins',
    'pom poms',
    'stencils',
    'wooden craft sticks',
    'paper plates',
    'pipe cleaners',
    'googly eyes',
    'feathers',
    'modeling clay',
    'origami paper',
    'paper punches',
    'paper clips',
    'rubber stamps',
    'ink pads',
    'ribbon bows',
    'cotton balls',
    'paper bags',
    'glue gun',
    'rhinestones',
    'jewelry findings',
    'craft wire',
    'adhesive tape',
    'calligraphy pens',
    'heat embossing tools',
    'cutting mats',
    'quilting rulers',
    'craft storage',
    'beading thread',
    'paint palettes',
    'paintbrush holders',
    'canvas panels',
    'charcoal pencils',
    'paint markers',
    'fabric paint',
    'stitching hoops',
    'cross-stitch kits',
    'embroidery hoops',
    'knitting yarn',
    'crochet thread',
    'felting needles',
    'sewing notions',
    'quilling paper',
    'scrapbook paper',
    'sticker sheets',
    'die-cut machines',
    'punching machines',
    'embossing folders',
    'jewelry making kits',
    'beading tools',
    'craft scissors',
    'craft punches',
    'paper trimmers',
    'embroidery scissors',
    'needle felting kits',
    'sewing patterns',
    'stitch markers',
    'fabric markers',
    'quilt batting',
    'sewing thread',
    'embroidery thread',
    'knitting patterns',
    'crochet patterns',
    'quilling tools',
    'scrapbooking tools',
    'adhesive dots',
    'paper clips',
    'rubber stamp sets',
    'ink refills',
    'glitter glue',
    'sticker embellishments',
    'rhinestone stickers',
    'jewelry making supplies',
    'beading wire',
    'adhesive sprays',
    'calligraphy ink',
    'embossing powders',
    'stencil brushes',
  ];
  
  console.log(artCraftTags);
  