const babyProductsTags: string[] = [
    'diapers',
    'baby wipes',
    'baby bottles',
    'pacifiers',
    'baby formula',
    'baby food',
    'baby bathtub',
    'baby shampoo',
    'baby lotion',
    'baby oil',
    'baby powder',
    'baby clothes',
    'baby onesies',
    'baby socks',
    'baby shoes',
    'baby hats',
    'baby blankets',
    'baby swaddles',
    'baby bibs',
    'baby towels',
    'baby washcloths',
    'baby carriers',
    'baby strollers',
    'baby car seats',
    'baby high chairs',
    'baby cribs',
    'baby bassinets',
    'baby changing tables',
    'baby playpens',
    'baby walkers',
    'baby bouncers',
    'baby jumpers',
    'baby toys',
    'baby rattles',
    'baby teethers',
    'baby mobiles',
    'baby activity gyms',
    'baby plush toys',
    'baby books',
    'baby monitors',
    'baby humidifiers',
    'baby thermometers',
    'baby safety gates',
    'baby outlet covers',
    'baby cabinet locks',
    'baby corner guards',
    'baby bottle sterilizers',
    'baby bottle warmers',
    'baby nasal aspirators',
    'baby nail clippers',
    'baby hairbrush',
    'baby toothbrush',
    'baby bath thermometer',
    'baby feeding spoons',
    'baby sippy cups',
    'baby food storage containers',
    'baby pacifier clips',
    'baby diaper bags',
    'baby changing pads',
    'baby nursing pillows',
    'baby bottle brushes',
    'baby bath toys',
    'baby bath seat',
    'baby bath towels',
    'baby bathrobe',
    'baby swim diapers',
    'baby sunscreen',
    'baby insect repellent',
    'baby first aid kit',
    'baby medicine dropper',
    'baby teething gel',
    'baby nasal saline solution',
    'baby laundry detergent',
    'baby hangers',
    'baby closet dividers',
    'baby drawer organizers',
    'baby diaper pail',
    'baby laundry hamper',
    'baby wet bags',
    'baby mattress',
    'baby crib sheets',
    'baby crib mobile',
    'baby crib mattress protector',
    'baby sleep sacks',
    'baby sleep sound machines',
    'baby night lights',
    'baby nursery decor',
    'baby photo frames',
    'baby milestone cards',
    'baby memory books',
    'baby diaper rash cream',
    'baby gas relief drops',
    'baby gripe water',
    'baby oral care kit',
    'baby grooming kit',
    'baby massage oil',
  ];
  
  console.log(babyProductsTags);
  