const bagsCasesTags: string[] = [
    'backpacks',
    'handbags',
    'tote bags',
    'laptop bags',
    'briefcases',
    'shoulder bags',
    'crossbody bags',
    'clutches',
    'duffel bags',
    'gym bags',
    'travel bags',
    'rolling suitcases',
    'luggage sets',
    'carry-on bags',
    'garment bags',
    'camera bags',
    'diaper bags',
    'beach bags',
    'cooler bags',
    'lunch bags',
    'drawstring bags',
    'waist packs',
    'fanny packs',
    'wallets',
    'cardholders',
    'money clips',
    'passport holders',
    'keychain pouches',
    'makeup bags',
    'toiletry bags',
    'jewelry cases',
    'watch cases',
    'sunglasses cases',
    'tablet cases',
    'laptop sleeves',
    'phone cases',
    'e-reader cases',
    'camera cases',
    'document holders',
    'portfolio cases',
    'briefcase organizers',
    'gadget organizers',
    'cable organizers',
    'travel organizers',
    'cosmetic organizers',
    'jewelry organizers',
    'drawer organizers',
    'storage bins',
    'laundry bags',
    'shoe bags',
    'garment covers',
    'shopping bags',
    'reusable grocery bags',
    'trolley bags',
    'bike bags',
    'pencil cases',
    'pen holders',
    'paintbrush holders',
    'art supply organizers',
    'musical instrument cases',
    'guitar bags',
    'violin cases',
    'drum bags',
    'keyboard bags',
    'gun cases',
    'first aid kits',
    'tool bags',
    'toolboxes',
    'lunch containers',
    'water bottle holders',
    'wet bags',
    'fireproof document bags',
    'camera lens cases',
    'hardshell suitcases',
    'softshell suitcases',
    'rolling backpacks',
    'laptop backpacks',
    'camera backpacks',
    'diaper backpacks',
    'trolley backpacks',
    'rolling duffel bags',
    'cooler backpacks',
    'toiletry travel kits',
    'travel jewelry cases',
    'travel shoe bags',
    'travel garment bags',
    'travel document wallets',
    'travel cosmetic bags',
    'travel toiletry organizers',
  ];
  
  console.log(bagsCasesTags);
  