const cleaningSuppliesTags: string[] = [
    'all-purpose cleaners',
    'bathroom cleaners',
    'kitchen cleaners',
    'floor cleaners',
    'window cleaners',
    'disinfectant wipes',
    'disinfectant sprays',
    'toilet cleaners',
    'glass cleaners',
    'stain removers',
    'carpet cleaners',
    'furniture polish',
    'wood cleaners',
    'stainless steel cleaners',
    'granite cleaners',
    'tile cleaners',
    'grout cleaners',
    'oven cleaners',
    'dish soaps',
    'dishwasher detergents',
    'laundry detergents',
    'fabric softeners',
    'bleach',
    'stain pre-treatments',
    'dryer sheets',
    'air fresheners',
    'odor eliminators',
    'mop heads',
    'broom heads',
    'dustpans',
    'sponges',
    'scrub brushes',
    'microfiber cloths',
    'latex gloves',
    'rubber gloves',
    'dishwashing gloves',
    'bucket',
    'mop',
    'broom',
    'dustpan and brush set',
    'vacuum cleaner',
    'carpet sweeper',
    'steam mop',
    'duster',
    'feather duster',
    'window squeegee',
    'toilet brush',
    'toilet plunger',
    'drying rack',
    'garbage bags',
    'trash cans',
    'trash can liners',
    'paper towels',
    'toilet paper',
    'facial tissues',
    'cleaning caddies',
    'storage containers',
    'storage baskets',
    'laundry baskets',
    'clothespins',
    'lint rollers',
    'step stool',
    'broom and mop holders',
    'vacuum cleaner bags',
    'vacuum cleaner filters',
    'cleaning gloves',
    'cleaning aprons',
    'cleaning masks',
    'dust masks',
    'mop buckets',
    'spray bottles',
    'extension poles',
    'dust masks',
    'cleaning brushes',
    'oven mitts',
    'dish drying mats',
    'cleaning cloths',
    'dust cloths',
    'cleaning solution refills',
    'spot cleaners',
    'pet stain removers',
    'grout brushes',
    'carpet deodorizers',
    'fabric refreshers',
    'air purifiers',
    'vacuum cleaner attachments',
    'dryer vent brushes',
    'duster refills',
    'broom handles',
    'cleaning wipes',
    'window cleaning kits',
    'microfiber mop pads',
    'squeegee handles',
    'mop refill pads',
    'mop and broom holders',
    'cleaning trolleys',
    'floor polishers',
  ];
  
  console.log(cleaningSuppliesTags);
  