const clothingTags: string[] = [
    't-shirts',
    'shirts',
    'blouses',
    'tops',
    'unisex',
    'sweaters',
    'hoodies',
    'jackets',
    'coats',
    'dresses',
    'skirts',
    'pants',
    'jeans',
    'shorts',
    'leggings',
    'activewear',
    'sportswear',
    'swimwear',
    'underwear',
    'bras',
    'panties',
    'boxers',
    'briefs',
    'socks',
    'stockings',
    'tights',
    'sleepwear',
    'pajamas',
    'robes',
    'lingerie',
    'nightgowns',
    'nightwear',
    'formalwear',
    'suits',
    'blazers',
    'dress shirts',
    'dress pants',
    'ties',
    'bowties',
    'accessories',
    'belts',
    'hats',
    'caps',
    'scarves',
    'gloves',
    'sunglasses',
    'wallets',
    'handbags',
    'backpacks',
    'shoulder bags',
    'tote bags',
    'crossbody bags',
    'clutches',
    'shoes',
    'sneakers',
    'boots',
    'sandals',
    'heels',
    'flats',
    'loafers',
    'slippers',
    'formal shoes',
    'casual shoes',
    'workout shoes',
    'running shoes',
    'sports shoes',
    'hiking shoes',
    'jewelry',
    'necklaces',
    'bracelets',
    'earrings',
    'rings',
    'watches',
    'anklets',
    'body jewelry',
    'brooches',
    'cufflinks',
    'tie pins',
    'hair accessories',
    'hats',
    'headbands',
    'hair clips',
    'hair ties',
    'hair bows',
    'cosmetics',
    'makeup',
    'foundation',
    'concealer',
    'powder',
    'blush',
    'highlighter',
    'eyeshadow',
    'eyeliner',
    'mascara',
    'lipstick',
    'lip gloss',
    'nail polish',
    'fragrances',
    'perfumes',
    'colognes',
    'body sprays',
    'deodorants',
    'skincare',
    'cleansers',
    'toners',
    'moisturizers',
    'serums',
    'face masks',
    'eye creams',
    'body lotions',
    'sunscreen',
    'bath and body',
    'body wash',
    'body scrub',
    'body butter',
    'shower gel',
    'hand cream',
    'foot cream',
    'nail care',
    'nail clippers',
    'nail files',
    'nail buffers',
    'nail polish remover',
    'intimate care',
    'feminine hygiene',
    'menstrual products',
    'bras',
    'panties',
    'shapewear',
    'Adidas',
  'H&M',
  'Zara',
  'Levi\'s',
  'Calvin Klein',
  'Tommy Hilfiger',
  'Gucci',
  'Prada',
  'Burberry',
  'Versace',
  'Chanel',
  'Dior',
  'Louis Vuitton',
  'Balenciaga',
  'Yves Saint Laurent',
  'Ralph Lauren',
  'Fendi',
  'Givenchy',
  'Valentino',
  'Hugo Boss',
  'Armani',
  'Diesel',
  'Puma',
  'Reebok',
  'Converse',
  'Vans',
  'The North Face',
  'Patagonia',
  'Columbia',
  'Under Armour',
  'Lululemon',
  'Gap',
  'Banana Republic',
  'J.Crew',
  'American Eagle',
  'Forever 21',
  'Old Navy',
  'Anthropologie',
  'Urban Outfitters',
  'Free People',
  'Madewell',
  'L.L.Bean',
  'Eddie Bauer',
  'Timberland',
  'Carhartt',
  'Wrangler',
  'Abercrombie & Fitch',
  'Hollister',
  'Victoria\'s Secret',
  'Aerie',
  'The Gap',
  'Aritzia',
  'Roots',
  'Canada Goose',
  'Lacoste',
  'Superdry',
  'ASOS',
  'Topshop',
  'River Island',
  'Primark',
  'Boohoo',
  'Next',
  'Mango',
  'Pull & Bear',
  'Stradivarius',
  'Bershka',
  'Oysho',
  'Massimo Dutti',
  'COS',
  'Weekday',
  'H&M Studio',
  '& Other Stories',
  'Monki',
  'Sandro',
  'Maje',
  'Zadig & Voltaire',
  'Comptoir des Cotonniers',
  'Uniqlo',
  'Muji',
  'Cosabella',
  'Hanky Panky',
  'Spanx',
  'La Perla',
  'Agent Provocateur',
  'Wolford',
  ];
  
  console.log(clothingTags);
  