const diyToolsTags: string[] = [
    'power tools',
    'hand tools',
    'screwdrivers',
    'wrenches',
    'pliers',
    'hammers',
    'saws',
    'drills',
    'grinders',
    'sanders',
    'nail guns',
    'staple guns',
    'measuring tools',
    'tape measures',
    'levels',
    'squares',
    'rulers',
    'marking tools',
    'chisels',
    'files',
    'scrapers',
    'knives',
    'cutting tools',
    'soldering',
    'welding',
    'gluing',
    'adhesives',
    'fasteners',
    'screws',
    'nails',
    'nuts and bolts',
    'anchors',
    'hooks',
    'brackets',
    'clamps',
    'vices',
    'ladders',
    'step stools',
    'workbenches',
    'storage',
    'toolboxes',
    'tool bags',
    'organizers',
    'workshop',
    'workshop equipment',
    'workshop supplies',
    'safety equipment',
    'gloves',
    'protective eyewear',
    'masks',
    'ear protection',
    'workwear',
    'aprons',
    'painting',
    'paint brushes',
    'rollers',
    'paint trays',
    'paint sprayers',
    'sandpaper',
    'paints',
    'stains',
    'varnishes',
    'sealants',
    'fillers',
    'caulking',
    'plumbing',
    'pipes',
    'fittings',
    'valves',
    'faucets',
    'plungers',
    'drain snakes',
    'electrical',
    'wiring',
    'outlets',
    'switches',
    'circuit breakers',
    'extension cords',
    'lighting',
    'bulbs',
    'fixtures',
    'ceiling fans',
    'home automation',
    'smart home',
    'security systems',
    'door locks',
    'doorbells',
    'thermostats',
    'home improvement',
    'renovation',
    'remodeling',
    'construction',
    'carpentry',
    'woodworking',
    'metalworking',
    'masonry',
    'tiling',
    'flooring',
    'plastering',
    'drywall',
    'insulation',
    'roofing',
    'fencing',
    'decking',
    'gates',
    'landscaping',
    'gardening',
    'planting',
    'pruning',
    'trimming',
    'irrigation',
    'garden tools',
    'greenhouse',
    'DIY projects',
    'home repairs',
    'home maintenance',
    'tool sets',
    'home renovation books',
    'DIY tutorials',
    'how-to guides',
    'DIY workshops',
    'tool rentals',
  ];
  
  console.log(diyToolsTags);
  