const electronicsTags: string[] = [
    'smartphones',
    'laptops',
    'tablets',
    'headphones',
    'speakers',
    'televisions',
    'cameras',
    'gaming consoles',
    'smartwatches',
    'fitness trackers',
    'printers',
    'monitors',
    'keyboards',
    'mice',
    'hard drives',
    'routers',
    'modems',
    'memory cards',
    'USB drives',
    'batteries',
    'chargers',
    'cables',
    'adapters',
    'power banks',
    'smart home devices',
    'virtual reality headsets',
    'drones',
    'robotic vacuum cleaners',
    'smart thermostats',
    'smart locks',
    'smart lighting',
    'smart plugs',
    'action cameras',
    'portable speakers',
    'wireless earphones',
    'bluetooth headphones',
    'gaming accessories',
    'gaming keyboards',
    'gaming mice',
    'gaming headsets',
    'gaming monitors',
    'gaming chairs',
    'car electronics',
    'car stereos',
    'car speakers',
    'car amplifiers',
    'car GPS',
    'car dash cameras',
    'car phone holders',
    'home theater systems',
    'soundbars',
    'projectors',
    'DVD players',
    'blu-ray players',
    'media streaming devices',
    'smart TVs',
    'sound systems',
    'digital cameras',
    'mirrorless cameras',
    'DSLR cameras',
    'instant cameras',
    'point-and-shoot cameras',
    'camera lenses',
    'camera tripods',
    'camera bags',
    'camera accessories',
    'lenses',
    'camera filters',
    'camera flashes',
    'memory card readers',
    'camera cleaning kits',
    'gaming laptops',
    'ultrabooks',
    '2-in-1 laptops',
    'gaming desktops',
    'all-in-one computers',
    'computer components',
    'processors',
    'graphics cards',
    'motherboards',
    'RAM',
    'SSDs',
    'HDDs',
    'computer cases',
    'power supplies',
    'computer cooling',
    'computer peripherals',
    'printers',
    'scanners',
    'projectors',
    'monitors',
    'keyboards',
    'mice',
    'webcams',
    'speakers',
    'headsets',
    'microphones',
    'drawing tablets',
    'graphics tablets',
    'stylus pens',
    'smartphones accessories',
    'phone cases',
    'screen protectors',
    'charging cables',
    'car mounts',
    'wireless chargers',
    'phone grips',
    'headphone adapters',
    'smartphone lenses',
    'selfie sticks',
    'mobile power banks',
    'tablets accessories',
    'tablet cases',
    'screen protectors',
    'stylus pens',
    'tablet keyboards',
    'tablet stands',
    'tablet mounts',
    'wireless speakers',
    'earphones',
    'over-ear headphones',
    'noise-cancelling headphones',
    'gaming headsets',
    'wireless headphones',
    'bluetooth speakers',
    'home speakers',
    'portable speakers',
  ];
  
  console.log(electronicsTags);
  