const footwearTags: string[] = [
    'sneakers',
    'running shoes',
    'athletic shoes',
    'sports shoes',
    'tennis shoes',
    'basketball shoes',
    'soccer shoes',
    'football shoes',
    'cleats',
    'hiking boots',
    'work boots',
    'winter boots',
    'rain boots',
    'sandals',
    'flip-flops',
    'slippers',
    'dress shoes',
    'loafers',
    'oxfords',
    'brogues',
    'derby shoes',
    'pumps',
    'heels',
    'wedges',
    'flats',
    'ballerina shoes',
    'moccasins',
    'boots',
    'ankle boots',
    'knee-high boots',
    'over-the-knee boots',
    'chelsea boots',
    'combat boots',
    'riding boots',
    'workout shoes',
    'gym shoes',
    'training shoes',
    'skate shoes',
    'skateboarding shoes',
    'slip-on shoes',
    'canvas shoes',
    'espadrilles',
    'platform shoes',
    'slingback shoes',
    'mary jane shoes',
    'boat shoes',
    'mules',
    'clogs',
    'safety shoes',
    'steel toe shoes',
    'water shoes',
    'dance shoes',
    'tap shoes',
    'ballet shoes',
    'jazz shoes',
    'character shoes',
    'cheerleading shoes',
    'golf shoes',
    'bowling shoes',
    'cycling shoes',
    'climbing shoes',
    'weightlifting shoes',
    'barefoot shoes',
    'diabetic shoes',
    'orthopedic shoes',
    'wide width shoes',
    'narrow width shoes',
    'extra cushioned shoes',
    'memory foam shoes',
    'arch support shoes',
    'plantar fasciitis shoes',
    'shoe accessories',
    'shoe care',
    'shoe polish',
    'shoe cleaner',
    'shoe laces',
    'shoe insoles',
    'shoe inserts',
    'shoe bags',
    'shoe organizers',
    'shoe racks',
    'shoe shelves',
    'shoe storage',
    'shoe repair',
    'shoe stretching',
    'shoe waterproofing',
    'Alden',
    'Allen Edmonds',
    'Balenciaga',
    'Bally',
    'Berluti',
    'Birkenstock',
    'Bottega Veneta',
    'Buscemi',
    'Church\'s',
    'Clarks',
    'Cole Haan',
    'Common Projects',
    'Crocs',
    'Diadora',
    'Dior',
    'Dr. Martens',
    'Fila',
    'Filling Pieces',
    'Gucci',
    'Hoka One One',
    'J.Crew',
    'Jimmy Choo',
    'Lacoste',
    'Le Coq Sportif',
    'Loewe',
    'Magnanni',
    'Maison Margiela',
    'Merrell',
    'Mephisto',
    'Miu Miu',
    'Moncler',
    'Onitsuka Tiger',
    'Oofos',
    'Paul Smith',
    'Prada',
    'Red Wing Shoes',
    'Rick Owens',
    'Rothy\'s',
    'Saint Laurent',
    'Salvatore Ferragamo',
    'Santoni',
    'Skechers',
    'Sperry',
    'Steve Madden',
    'Stuart Weitzman',
    'Superga',
    'Tod\'s',
    'Timberland',
    'Tommy Hilfiger',
    'Ugg',
    'Valentino',
    'Veja',
    'Versace',
    'Y-3',
    'Yeezy',
    'Zara',
    'Zegna',
  ];
  
  console.log(footwearTags);
  