const homeOfficeTags: string[] = [
    'bedding',
    'bed sheets',
    'duvet covers',
    'comforters',
    'pillows',
    'mattress toppers',
    'blankets',
    'throws',
    'quilts',
    'bedspreads',
    'mattresses',
    'bed frames',
    'headboards',
    'nightstands',
    'dressers',
    'chests',
    'wardrobes',
    'armoires',
    'vanities',
    'bedroom sets',
    'sofas',
    'sectional sofas',
    'loveseats',
    'recliners',
    'accent chairs',
    'ottomans',
    'chaise lounges',
    'coffee tables',
    'end tables',
    'console tables',
    'TV stands',
    'entertainment centers',
    'bookcases',
    'shelving units',
    'cabinets',
    'dining tables',
    'dining chairs',
    'bar stools',
    'sideboards',
    'buffets',
    'china cabinets',
    'kitchen islands',
    'pantry cabinets',
    'benches',
    'desks',
    'office chairs',
    'file cabinets',
    'bookshelves',
    'desk organizers',
    'desk lamps',
    'desk accessories',
    'rugs',
    'area rugs',
    'runners',
    'outdoor rugs',
    'doormats',
    'carpets',
    'curtains',
    'drapes',
    'blinds',
    'shades',
    'window treatments',
    'curtain rods',
    'curtain hooks',
    'tiebacks',
    'blinds accessories',
    'shower curtains',
    'bathroom mats',
    'bath towels',
    'hand towels',
    'washcloths',
    'shower caddies',
    'shower dispensers',
    'toilet paper holders',
    'towel racks',
    'bathroom shelves',
    'bathroom storage',
    'bathroom mirrors',
    'vanity mirrors',
    'bathroom accessories',
    'bedroom decor',
    'living room decor',
    'dining room decor',
    'kitchen decor',
    'bathroom decor',
    'wall art',
    'paintings',
    'prints',
    'photographs',
    'wall sculptures',
    'wall decals',
    'mirrors',
    'clocks',
    'vases',
    'candles',
    'candle holders',
    'votive holders',
    'scented candles',
    'table lamps',
    'floor lamps',
    'chandeliers',
    'pendant lights',
    'ceiling lights',
    'string lights',
    'lamp shades',
    'fireplaces',
    'fireplace tools',
    'fireplace screens',
    'fireplace accessories',
    'indoor fountains',
    'throw pillows',
    'cushions',
    'throws',
    'afghans',
    'bean bags',
    'storage baskets',
    'storage bins',
    'storage boxes',
    'shoe racks',
    'laundry hampers',
    'laundry baskets',
    'closet organizers',
    'garment racks',
    'coatracks',
    'umbrella stands',
    'room dividers',
    'partitions',
    'window seats',
    'window benches',
    'window cushions',
    'window blinds',
    'window shades',
  ];
  
  console.log(homeOfficeTags);
  