const jewelleryTags: string[] = [
    'necklaces',
    'pendants',
    'chains',
    'chokers',
    'bracelets',
    'bangles',
    'cufflinks',
    'rings',
    'earrings',
    'hoop earrings',
    'stud earrings',
    'dangle earrings',
    'drop earrings',
    'ear cuffs',
    'anklets',
    'brooches',
    'pins',
    'charms',
    'lockets',
    'birthstone jewellery',
    'pearl jewellery',
    'diamond jewellery',
    'gemstone jewellery',
    'gold jewellery',
    'silver jewellery',
    'platinum jewellery',
    'rose gold jewellery',
    'vintage jewellery',
    'fashion jewellery',
    'statement jewellery',
    'bridal jewellery',
    'wedding rings',
    'engagement rings',
    'promise rings',
    'anniversary rings',
    'cocktail rings',
    'stackable rings',
    'toe rings',
    'jewellery sets',
    'jewellery boxes',
    'jewellery organizers',
    'watch bands',
    'watch accessories',
    'bracelet watches',
    'dress watches',
    'chronograph watches',
    'automatic watches',
    'smartwatches',
    'fob watches',
    'pocket watches',
    'tie clips',
    'money clips',
    'keychains',
    'jewellery cleaning kits',
    'jewellery polish',
    'jewellery storage',
    'jewellery display',
    'body jewellery',
    'nose rings',
    'lip rings',
    'eyebrow rings',
    'belly button rings',
    'nipple rings',
    'tongue rings',
    'captured bead rings',
    'body chains',
    'ankle bracelets',
    'jewellery for men',
    'jewellery for women',
    'jewellery for kids',
    'personalized jewellery',
    'initial jewellery',
    'name necklaces',
    'monogram jewellery',
    'birthstone jewellery',
    'engraved jewellery',
    'handmade jewellery',
    'beaded jewellery',
    'wire wrapped jewellery',
    'resin jewellery',
    'leather jewellery',
    'wooden jewellery',
    'shell jewellery',
    'boho jewellery',
    'ethnic jewellery',
    'tribal jewellery',
    'statement necklaces',
    'chunky necklaces',
    'layered necklaces',
    'chandelier earrings',
    'tassel earrings',
    'statement bracelets',
    'cuff bracelets',
    'layered bracelets',
    'statement rings',
    'cocktail rings',
    'stacking rings',
    'statement brooches',
    'vintage brooches',
    'pin brooches',
    'jewellery repair',
    'jewellery resizing',
    'jewellery cleaning',
    'jewellery maintenance',
  ];
  
  console.log(jewelleryTags);
  