const mediaTags: string[] = [
    'books',
    'eBooks',
    'audiobooks',
    'magazines',
    'newspapers',
    'comics',
    'graphic novels',
    'music',
    'albums',
    'singles',
    'vinyl records',
    'CDs',
    'cassettes',
    'digital music',
    'movies',
    'DVDs',
    'Blu-rays',
    '4K Ultra HD',
    'digital movies',
    'TV shows',
    'box sets',
    'streaming media',
    'video games',
    'console games',
    'PC games',
    'Nintendo Switch games',
    'PlayStation games',
    'Xbox games',
    'VR games',
    'mobile games',
    'board games',
    'card games',
    'puzzles',
    'educational media',
    'documentaries',
    'educational books',
    'educational apps',
    'art supplies',
    'painting',
    'drawing',
    'sketching',
    'crafting',
    'sculpting',
    'photography',
    'editing software',
    'printing services',
    'musical instruments',
    'guitars',
    'pianos',
    'drums',
    'violin',
    'flute',
    'trumpet',
    'saxophone',
    'microphones',
    'audio equipment',
    'studio recording',
    'music lessons',
    'dance',
    'ballet',
    'hip hop',
    'salsa',
    'tango',
    'tap',
    'theater',
    'plays',
    'musicals',
    'tickets',
    'concerts',
    'live events',
    'sports',
    'sporting events',
    'fitness',
    'workout videos',
    'exercise equipment',
    'yoga',
    'meditation',
    'cooking',
    'cookbooks',
    'recipes',
    'cooking shows',
    'culinary classes',
    'travel',
    'travel books',
    'travel guides',
    'travel documentaries',
    'language learning',
    'language courses',
    'language apps',
    'self-help',
    'inspirational books',
    'motivational speakers',
    'personal development',
    'productivity',
    'business',
    'entrepreneurship',
    'finance',
    'investing',
    'economics',
    'technology',
    'science',
    'nature',
    'environment',
    'history',
    'biographies',
    'autobiographies',
    'true crime',
    'fiction',
    'fantasy',
    'science fiction',
    'mystery',
    'romance',
    'thriller',
    'horror',
    'poetry',
    'literary classics',
    'children\'s books',
    'young adult',
    'comic books',
    'graphic novels',
    'music documentaries',
    'film documentaries',
    'video game documentaries',
    'art documentaries',
    'educational documentaries',
    'sports documentaries',
    'nature documentaries',
    'travel documentaries',
    'historical documentaries',
    'science documentaries',
  ];
  
  console.log(mediaTags);
  