const musicTags: string[] = [
    'rock',
    'pop',
    'hip hop',
    'rap',
    'country',
    'alternative',
    'indie',
    'electronic',
    'dance',
    'r&b',
    'soul',
    'jazz',
    'blues',
    'reggae',
    'classical',
    'folk',
    'punk',
    'metal',
    'instrumental',
    'world music',
    'latin',
    'k-pop',
    'j-pop',
    'gospel',
    'christian',
    'soundtracks',
    'compilations',
    'live recordings',
    'remixes',
    'acoustic',
    'covers',
    'original songs',
    'singer-songwriter',
    'boy bands',
    'girl groups',
    'duets',
    'solo artists',
    'music festivals',
    'concerts',
    'live performances',
    'music videos',
    'music streaming',
    'online music stores',
    'music production',
    'recording studios',
    'music equipment',
    'musical instruments',
    'music lessons',
    'sheet music',
    'music theory',
    'music notation',
    'music software',
    'music apps',
    'music events',
    'music industry',
    'music news',
    'music reviews',
    'music charts',
    'music awards',
    'music documentaries',
    'music history',
    'music genres',
    'music trivia',
    'music merch',
    'vinyl records',
    'CDs',
    'digital music',
    'music playlists',
    'music recommendations',
    'music blogs',
    'music podcasts',
    'music communities',
    'music forums',
    'music social media',
    'music education',
    'music therapy',
    'music research',
    'music careers',
    'music marketing',
    'music licensing',
    'music copyright',
    'music royalties',
    'music contracts',
  ];
  
  console.log(musicTags);
  