const occasionTags: string[] = [
    'birthday',
    'anniversary',
    'wedding',
    'engagement',
    'graduation',
    'retirement',
    'promotion',
    'baby shower',
    'bridal shower',
    'housewarming',
    'new job',
    'farewell',
    'get well soon',
    'thank you',
    'congratulations',
    'sympathy',
    'condolence',
    'thinking of you',
    'sorry',
    'apology',
    'love',
    'friendship',
    'just because',
    'holiday',
    'Christmas',
    'Easter',
    'Thanksgiving',
    'Valentine\'s Day',
    'Mother\'s Day',
    'Father\'s Day',
    'Halloween',
    'New Year',
    'Independence Day',
    'Hanukkah',
    'Kwanzaa',
    'religious',
    'religious ceremonies',
    'religious holidays',
    'religious events',
    'religious milestones',
    'religious celebrations',
    'graduation party',
    'wedding party',
    'baby shower party',
    'bridal shower party',
    'engagement party',
    'retirement party',
    'promotion party',
    'farewell party',
    'welcome party',
    'surprise party',
    'cocktail party',
    'dinner party',
    'tea party',
    'BBQ party',
    'picnic party',
    'pool party',
    'beach party',
    'garden party',
    'themed party',
    'costume party',
    'masquerade party',
    'casual party',
    'formal party',
    'outdoor party',
    'indoor party',
    'family gathering',
    'reunion',
    'office party',
    'corporate event',
    'charity event',
    'fundraising event',
    'business conference',
    'seminar',
    'workshop',
    'trade show',
    'product launch',
    'networking event',
    'awards ceremony',
    'art exhibition',
    'concert',
    'theater performance',
    'dance performance',
    'sports event',
    'sporting competition',
    'movie premiere',
    'film festival',
    'book signing',
    'literary event',
    'fashion show',
    'gala dinner',
    'black-tie event',
    'red carpet event',
    'VIP event',
    'private event',
    'public event',
    'celebration',
    'festivity',
    'commemoration',
    'ceremony',
    'ritual',
    'memorial',
    'tribute',
    'gathering',
    'party',
    'halloween',
    'event planning',
    'event coordination',
    'event management',
    'event decorations',
    'event invitations',
    'event catering',
    'event rentals',
    'event entertainment',
    'event photography',
    'event videography',
    'event marketing',
    'event promotion',
    'flowers',
    'flower',
    'event tickets',
  ];
  
  console.log(occasionTags);
  