const outdoorLivingTags: string[] = [
    'patio furniture',
    'outdoor sofas',
    'outdoor sectionals',
    'outdoor dining sets',
    'outdoor tables',
    'outdoor chairs',
    'outdoor benches',
    'outdoor loungers',
    'hammocks',
    'porch swings',
    'outdoor umbrellas',
    'outdoor cushions',
    'patio heaters',
    'fire pits',
    'outdoor lighting',
    'outdoor rugs',
    'outdoor decor',
    'outdoor planters',
    'outdoor fountains',
    'outdoor statues',
    'outdoor wall art',
    'grills',
    'outdoor cooking equipment',
    'outdoor dinnerware',
    'picnic baskets',
    'coolers',
    'outdoor storage',
    'deck boxes',
    'storage benches',
    'outdoor sheds',
    'gardening tools',
    'plant pots',
    'garden hoses',
    'watering cans',
    'gardening gloves',
    'gardening accessories',
    'outdoor games',
    'badminton sets',
    'cornhole sets',
    'croquet sets',
    'bocce ball sets',
    'lawn darts',
    'outdoor sports equipment',
    'bikes',
    'skateboards',
    'rollerblades',
    'scooters',
    'trampolines',
    'outdoor toys',
    'playhouses',
    'swing sets',
    'sandbox',
    'water slides',
    'outdoor pet supplies',
    'dog houses',
    'cat houses',
    'birdhouses',
    'outdoor pest control',
    'insect repellents',
    'bug zappers',
    'outdoor cleaning supplies',
    'pressure washers',
    'outdoor brooms',
    'outdoor storage covers',
    'outdoor furniture covers',
    'grill covers',
    'patio umbrella covers',
    'fire pit covers',
    'outdoor equipment covers',
    'outdoor safety',
    'outdoor first aid kits',
    'sunscreen',
    'bug sprays',
    'emergency whistles',
    'outdoor apparel',
    'hats',
    'sunglasses',
    'sun hats',
    'outdoor footwear',
    'hiking boots',
    'sandals',
    'water shoes',
    'outdoor clothing',
    'rain jackets',
    'windbreakers',
    'hiking pants',
    'outdoor accessories',
    'backpacks',
    'water bottles',
    'camping gear',
    'sleeping bags',
    'camping tents',
    'camping chairs',
    'camping stoves',
    'camping lanterns',
    'camping cookware',
    'camping utensils',
    'camping hammocks',
    'camping tarps',
  ];
  
  console.log(outdoorLivingTags);
  