const personalCareTags: string[] = [
    'skincare',
    'cleansers',
    'moisturizers',
    'serums',
    'face masks',
    'facial scrubs',
    'toners',
    'essences',
    'eye creams',
    'lip care',
    'sunscreen',
    'body care',
    'body wash',
    'body lotion',
    'body oil',
    'body butter',
    'hand cream',
    'foot care',
    'shower gel',
    'bath bombs',
    'bath salts',
    'deodorant',
    'antiperspirant',
    'hair care',
    'shampoo',
    'conditioner',
    'hair mask',
    'hair oil',
    'hair serum',
    'hair spray',
    'hair gel',
    'hair wax',
    'styling tools',
    'hairbrushes',
    'combs',
    'hairdryers',
    'curling irons',
    'straighteners',
    'electric shavers',
    'razors',
    'shaving cream',
    'aftershave',
    'beard care',
    'fragrances',
    'perfumes',
    'colognes',
    'body mists',
    'essential oils',
    'oral care',
    'toothpaste',
    'toothbrushes',
    'mouthwash',
    'dental floss',
    'lip balm',
    'feminine care',
    'sanitary pads',
    'tampons',
    'menstrual cups',
    'intimate wash',
    'shaving cream',
    'waxing',
    'nail care',
    'nail polish',
    'nail polish remover',
    'nail tools',
    'manicure sets',
    'pedicure sets',
    'foot files',
    'callus removers',
    'massage',
    'massage oils',
    'massage tools',
    'medicines',
    'pain relievers',
    'fever reducers',
    'cough syrup',
    'allergy medication',
    'vitamins',
    'supplements',
    'weight management',
    'dietary aids',
    'sleep aids',
    'eye care',
    'contact lenses',
    'contact lens solution',
    'eye drops',
    'eye masks',
    'first aid',
    'band-aids',
    'antiseptics',
    'bandages',
    'hot/cold packs',
    'medical equipment',
    'thermometers',
    'blood pressure monitors',
    'personal care accessories',
    'mirrors',
    'toiletry bags',
    'travel kits',
    'cosmetic cases',
    'makeup brushes',
    'makeup sponges',
    'cosmetic organizers',
    'shower caps',
    'bath accessories',
    'toilet paper',
    'tissues',
    'cotton pads',
    'cotton swabs',
    'wet wipes',
  ];
  
  console.log(personalCareTags);
  