const petSuppliesTags: string[] = [
  'dog food',
  'cat food',
  'dog treats',
  'cat treats',
  'dog toys',
  'cat toys',
  'dog bed',
  'cat bed',
  'dog collar',
  'cat collar',
  'dog leash',
  'cat leash',
  'dog grooming',
  'cat grooming',
  'dog shampoo',
  'cat shampoo',
  'dog bowl',
  'cat bowl',
  'dog crate',
  'cat crate',
  'dog carrier',
  'cat carrier',
  'dog harness',
  'cat harness',
  'dog training pads',
  'cat litter',
  'cat litter box',
  'cat scratching post',
  'bird cage',
  'fish tank',
  'hamster cage',
  'rabbit hutch',
  'guinea pig cage',
  'reptile terrarium',
  'small animal bedding',
  'bird food',
  'fish food',
  'hamster food',
  'rabbit food',
  'guinea pig food',
  'reptile food',
  'bird toys',
  'fish tank decorations',
  'hamster wheel',
  'rabbit hay',
  'guinea pig hay',
  'reptile heat lamp',
  'small animal water bottle',
  'bird cage accessories',
  'fish tank filter',
  'hamster bedding',
  'rabbit litter',
  'guinea pig bedding',
  'reptile substrate',
  'small animal treats',
  'bird cage perches',
  'fish tank air pump',
  'hamster exercise ball',
  'rabbit toys',
  'guinea pig toys',
  'reptile hiding cave',
  'small animal hay rack',
  'bird cages covers',
  'fish tank heater',
  'hamster hideout',
  'rabbit water bottle',
  'guinea pig water bottle',
  'reptile UVB light',
  'small animal nail clippers',
  'bird nest boxes',
  'fish tank thermometer',
  'hamster chew toys',
  'rabbit litter box',
  'guinea pig litter box',
  'reptile basking spot',
  'small animal litter',
  'bird bath',
  'fish tank gravel',
  'hamster exercise wheel',
  'rabbit litter scoop',
  'guinea pig hay rack',
  'reptile water dish',
  'small animal playpen',
  'bird perches',
  'fish tank light',
  'hamster water bottle',
  'rabbit litter pan',
  'guinea pig litter pan',
  'reptile humidity gauge',
  'small animal tunnel',
  'bird toys with bells',
  'fish tank background',
  'hamster ball',
  'rabbit litter tray',
  'guinea pig litter tray',
  'reptile thermostat',
  'small animal hut',
  'bird food dishes',
  'fish tank plants',
  'hamster bedding material',
  'rabbit litter mat',
  'guinea pig litter mat',
  'reptile feeding dish',
  'small animal exercise ball',
];

console.log(petSuppliesTags);
