const sportingGoodsTags: string[] = [
    'football',
    'soccer',
    'basketball',
    'baseball',
    'softball',
    'volleyball',
    'tennis',
    'golf',
    'hockey',
    'lacrosse',
    'rugby',
    'cricket',
    'badminton',
    'table tennis',
    'swimming',
    'diving',
    'water polo',
    'surfing',
    'skateboarding',
    'roller skating',
    'ice skating',
    'skiing',
    'snowboarding',
    'cross-country skiing',
    'snowshoeing',
    'hiking',
    'camping',
    'climbing',
    'bouldering',
    'mountaineering',
    'cycling',
    'road biking',
    'mountain biking',
    'bmx',
    'running',
    'jogging',
    'trail running',
    'marathon',
    'triathlon',
    'fitness',
    'exercise',
    'weightlifting',
    'strength training',
    'yoga',
    'pilates',
    'aerobics',
    'cardio',
    'jump rope',
    'boxing',
    'martial arts',
    'wrestling',
    'gymnastics',
    'dancing',
    'skipping rope',
    'exercise equipment',
    'treadmill',
    'exercise bike',
    'elliptical trainer',
    'rowing machine',
    'weight bench',
    'dumbbells',
    'kettlebells',
    'resistance bands',
    'medicine balls',
    'fitness trackers',
    'sports apparel',
    'jerseys',
    'shorts',
    't-shirts',
    'tank tops',
    'hoodies',
    'jackets',
    'leggings',
    'sports bras',
    'socks',
    'shoes',
    'cleats',
    'helmets',
    'pads',
    'gloves',
    'goggles',
    'sunglasses',
    'water bottles',
    'backpacks',
    'duffel bags',
    'sports bags',
    'equipment bags',
    'coaching',
    'training',
    'sports medicine',
    'first aid',
    'sports nutrition',
    'hydration',
    'recovery',
    'team sports',
    'individual sports',
    'competitive sports',
    'recreational sports',
    'outdoor sports',
    'indoor sports',
    'sporting events',
    'sports leagues',
    'sports tournaments',
    'sports camps',
    'sports clubs',
    'sports facilities',
    'sports training',
    'sports coaching',
    'sports psychology',
    'sports injuries',
    'sports recovery',
    'sports performance',
  ];
  
  console.log(sportingGoodsTags);
  