const toysTags: string[] = [
    'action figures',
    'dolls',
    'stuffed animals',
    'building blocks',
    'puzzles',
    'board games',
    'card games',
    'educational toys',
    'STEM toys',
    'art supplies',
    'craft kits',
    'model kits',
    'remote control toys',
    'vehicles',
    'trains',
    'drones',
    'robots',
    'pretend play',
    'kitchen sets',
    'doctor kits',
    'tool sets',
    'musical instruments',
    'outdoor toys',
    'sports toys',
    'ride-on toys',
    'bikes',
    'scooters',
    'skateboards',
    'water toys',
    'pools',
    'sandboxes',
    'playhouses',
    'trampolines',
    'swing sets',
    'kites',
    'gardening toys',
    'electronic toys',
    'interactive toys',
    'virtual reality',
    'augmented reality',
    'coding toys',
    'smart toys',
    'puppets',
    'magic sets',
    'pogo sticks',
    'bounce houses',
    'balance bikes',
    'stilts',
    'juggling',
    'yo-yos',
    'marbles',
    'collectible toys',
    'action figures',
    'trading cards',
    'plush toys',
    'toy vehicles',
    'dollhouses',
    'playsets',
    'dress-up',
    'costumes',
    'make-believe',
    'party supplies',
    'birthday',
    'themed parties',
    'play tents',
    'magnetic toys',
    'puppet theaters',
    'art easels',
    'toy instruments',
    'telescopes',
    'microscopes',
    'magic tricks',
    'building sets',
    'model trains',
    'doll accessories',
    'construction toys',
    'wooden toys',
    'plastic toys',
    'metal toys',
    'foam toys',
    'puzzle toys',
    'learning toys',
    'robotics kits',
    'science kits',
    'engineering toys',
    'math toys',
    'alphabet toys',
    'counting toys',
    'memory games',
    'coordination toys',
    'problem-solving toys',
    'imaginative toys',
    'creative toys',
    'outdoor play',
    'indoor play',
    'water play',
    'sandbox play',
    'toy storage',
    'toy organization',
    'toy cleaning',
    'toy safety',
    'toy reviews',
    'toy trends',
  ];
  
  console.log(toysTags);
  